[workenv.env]
siblings = [
    # Pattern for all pyvider packages
    { pattern = "pyvider-*", with_deps = true },
    # Other special packages  
    { name = "flavor", with_deps = true },
    { name = "wrkenv", with_deps = true }
]